// The public landing page follows the same languages as the app settings.
export const landingCopy = {
  ko: {
    tuiWindowsReq: '64비트 Windows PowerShell에서 아래 명령을 실행하세요. Windows용 실행 파일을 내려받아 설치하므로 Go나 C 컴파일러가 필요하지 않습니다.', tuiWindowsAfter: '설치 후 같은 PowerShell에서 ginote-tui를 실행하세요. 실행 파일은 %LOCALAPPDATA%\\Programs\\ginote-tui에 설치하고 사용자 PATH에 자동으로 추가합니다. 갱신할 때는 TUI를 종료한 뒤 설치 명령을 다시 실행하세요.',
    title: 'Ginote — 내 GitHub 저장소에 남는 노트', lead: '가볍고 심플한 나만의 노트 앱. GitHub Issues와 연동되어 개발 공간과 MCP 도구에서도 같은 노트를 사용할 수 있습니다.', previewAlt: 'Ginote에서 노트를 열고 편집하는 화면', start: '바로 시작', download: '다운로드', caption: 'GitHub 계정, 개인 저장소, 접근 토큰이 필요합니다. 시작 단계에서 차례로 안내합니다.', featuresLabel: 'Ginote 특징', features: [{ title: 'MCP와 완전 통합', body: '노트가 GitHub Issues에 저장되어 GitHub API와 공식 MCP Server에서 그대로 읽고 쓸 수 있습니다.' }, { title: '한 번 더 잠금', body: '비공개 저장소에 보관한 노트라도, 원한다면 본문에 잠금을 걸어 암호화할 수 있습니다.' }, { title: '웹과 앱, 터미널', body: '브라우저와 설치형 앱, TUI에서 같은 저장소를 사용할 수 있습니다.' }], mcpGuide: 'MCP 사용 방법 ↗',
    cards: { macos: 'DMG 설치 파일 또는 Homebrew로 설치합니다.', windows: 'Microsoft Store 없이 설치 파일을 내려받아 설치합니다.', linux: 'AppImage, deb, rpm 중에서 선택합니다.', tui: '터미널에서 한 줄 명령으로 빌드하고 설치합니다.' }, installMethod: '설치 방법', view: '보기 ↓', hide: '접기 ↑', latest: '최신 릴리스', copy: '명령 복사', copied: '명령을 복사했습니다.', copyFailed: '복사하지 못했습니다. 위 명령을 직접 복사해 주세요.',
    macTitle: 'macOS에서 설치하기', macChoose: '아래 두 방법 중 하나를 선택하세요.', dmg: 'DMG 파일로 설치', dmgStep1: '의 Assets에서 universal.dmg로 끝나는 파일을 받으세요.', dmgStep2: 'DMG를 열어 Ginote를 Applications 폴더로 옮기고 앱을 실행하세요.', homebrew: 'Homebrew로 설치', runCommand: '명령을 복사해 터미널에서 실행하세요.',
    linuxTitle: 'Linux에서 설치하기', linuxIntro: '의 Assets에서 배포판에 맞는 파일을 받으세요.', appImage: '파일에 실행 권한을 주고 실행합니다:',
    tuiTitle: '터미널에서 TUI 설치하기', tuiReq: 'Go 1.27.1 이상과 C 컴파일러가 필요합니다. 다음 명령을 터미널에 붙여 넣으면 소스를 내려받아 ~/.local/bin/ginote-tui에 설치합니다.', tuiAfter: '설치 후 ginote-tui를 실행하세요. 명령을 찾지 못하면 ~/.local/bin을 PATH에 추가하세요.', tuiPrebuilt: '미리 빌드된 파일은', tuiReleaseLabel: 'GitHub Releases의 tui-v... 태그', tuiPrebuiltEnd: '에서 받을 수 있습니다.', installScript: '설치 스크립트 보기', tuiDocs: 'TUI 상세 문서',
    windowsTitle: 'Windows에서 설치하기', windowsIntro: 'Microsoft Store 등록 없이 GitHub Releases에서 직접 설치합니다. 설치 파일에 Windows 코드 서명이 없어 처음 실행할 때 확인 화면이 나타날 수 있습니다.', windowsStep1: '의 Assets에서 이름이 x64-setup.exe로 끝나는 파일을 받으세요.', windowsStep2: '다운로드한 설치 파일을 실행하세요. “Windows의 PC 보호” 화면이 나오면 “추가 정보”를 누르세요.', windowsStep3: '파일 이름이 받은 Ginote 설치 파일과 같은지 확인하고 “실행”을 눌러 설치를 마치세요.', windowsNote: '브라우저 자체가 다운로드를 막으면 다운로드 목록에서 파일의 메뉴를 열어 “유지”를 선택해야 할 수 있습니다. 출처가 github.com/zidell/ginote인지 먼저 확인하세요. Windows의 Smart App Control이 파일을 완전히 차단하면 “추가 정보” 버튼이 없을 수 있습니다.', exampleLabel: '화면 예시 · Windows 버전에 따라 다를 수 있습니다', protect: 'Windows의 PC 보호', protectMsg: 'Microsoft Defender SmartScreen에서 인식할 수 없는 앱의 시작을 차단했습니다.', moreInfo: '① 추가 정보', app: '앱', publisher: '게시자: 알 수 없는 게시자', run: '② 실행',
    pwa: '브라우저에서도 설치할 수 있습니다. 이 페이지를 브라우저의 “앱 설치” 메뉴로 추가하면 다음부터 저장소 설정 화면으로 바로 열립니다.', source: '소스 코드'
  },
  en: {
    tuiWindowsReq: 'Run this command in 64-bit Windows PowerShell. It installs a prebuilt Windows executable, so Go and a C compiler are not required.', tuiWindowsAfter: 'After installation, run ginote-tui in the same PowerShell session. The installer uses %LOCALAPPDATA%\\Programs\\ginote-tui and adds it to your user PATH. To update, close the TUI and run the installer again.',
    title: 'Ginote — Notes in your GitHub repository', lead: 'A light, simple notes app for your own space. Notes live in GitHub Issues, so they work with your development workflow and MCP tools.', previewAlt: 'A note open for editing in Ginote', start: 'Get started', download: 'Download', caption: 'You will need a GitHub account, a private repository, and an access token. We will guide you through setup.', featuresLabel: 'Ginote features', features: [{ title: 'Built for MCP', body: 'Notes are GitHub Issues, ready to read and write through the GitHub API and official MCP Server.' }, { title: 'An extra lock', body: 'Your private repository already protects access. You can also encrypt the body of individual notes.' }, { title: 'Web, app, terminal', body: 'Use the same repository in a browser, installed app, or terminal TUI.' }], mcpGuide: 'How to use MCP ↗',
    cards: { macos: 'Install with a DMG or Homebrew.', windows: 'Download the installer directly, without Microsoft Store.', linux: 'Choose an AppImage, deb, or rpm package.', tui: 'Build and install from one terminal command.' }, installMethod: 'Installation', view: 'Show ↓', hide: 'Hide ↑', latest: 'latest release', copy: 'Copy command', copied: 'Command copied.', copyFailed: 'Could not copy. Please copy the command above manually.',
    macTitle: 'Install on macOS', macChoose: 'Choose one of these methods.', dmg: 'Install from DMG', dmgStep1: ': open Assets and download the file ending in universal.dmg.', dmgStep2: 'Open the DMG, drag Ginote to Applications, then launch the app.', homebrew: 'Install with Homebrew', runCommand: 'Copy and run these commands in Terminal.',
    linuxTitle: 'Install on Linux', linuxIntro: ': open Assets and download the file for your distribution.', appImage: 'Make the file executable and run it:',
    tuiTitle: 'Install the terminal TUI', tuiReq: 'Requires Go 1.27.1 or newer and a C compiler. Paste this command into your terminal to build the source and install it at ~/.local/bin/ginote-tui.', tuiAfter: 'Run ginote-tui after installation. If the command is not found, add ~/.local/bin to PATH.', tuiPrebuilt: 'Prebuilt files are available in', tuiReleaseLabel: 'GitHub Releases under a tui-v... tag', tuiPrebuiltEnd: '.', installScript: 'View install script', tuiDocs: 'TUI documentation',
    windowsTitle: 'Install on Windows', windowsIntro: 'Install directly from GitHub Releases without Microsoft Store. Since the installer is not code signed for Windows, you may see a confirmation screen the first time.', windowsStep1: ': open Assets and download the file ending in x64-setup.exe.', windowsStep2: 'Run the downloaded installer. If “Windows protected your PC” appears, click “More info”.', windowsStep3: 'Check that the file name matches the Ginote installer you downloaded, then click “Run anyway” to finish.', windowsNote: 'If your browser blocks the download, open its downloads list and choose “Keep” from the file menu. First check that the source is github.com/zidell/ginote. If Smart App Control blocks the file completely, the “More info” button may be unavailable.', exampleLabel: 'Example screen · may vary by Windows version', protect: 'Windows protected your PC', protectMsg: 'Microsoft Defender SmartScreen prevented an unrecognized app from starting.', moreInfo: '① More info', app: 'App', publisher: 'Publisher: Unknown publisher', run: '② Run anyway',
    pwa: 'You can also install the web app from your browser’s “Install app” menu. Next time, it will open directly to repository setup.', source: 'Source code'
  }
};

Object.assign(landingCopy, {
  'zh-CN': {
    ...landingCopy.en,
    tuiWindowsReq: '在 64 位 Windows PowerShell 中运行以下命令。它会安装预编译的 Windows 程序，不需要 Go 或 C 编译器。', tuiWindowsAfter: '安装后，在同一个 PowerShell 中运行 ginote-tui。程序安装到 %LOCALAPPDATA%\\Programs\\ginote-tui，并自动加入用户 PATH。更新时，请先关闭 TUI，再运行安装命令。',
    title: 'Ginote — 保存在 GitHub 仓库中的笔记', lead: '轻巧简洁的私人笔记应用。笔记存储为 GitHub Issues，可在开发工作流和 MCP 工具中使用。', previewAlt: '在 Ginote 中打开并编辑笔记', start: '立即开始', download: '下载', caption: '需要 GitHub 账号、私有仓库和访问令牌。设置过程会逐步引导您完成。', featuresLabel: 'Ginote 功能', features: [{ title: '与 MCP 完全集成', body: '笔记就是 GitHub Issues，可通过 GitHub API 和官方 MCP Server 直接读写。' }, { title: '再加一道锁', body: '私有仓库已限制访问；您还可以加密单篇笔记的正文。' }, { title: '网页、应用和终端', body: '在浏览器、桌面应用或终端 TUI 中使用同一个仓库。' }], mcpGuide: 'MCP 使用方法 ↗',
    cards: { macos: '使用 DMG 或 Homebrew 安装。', windows: '无需 Microsoft Store，直接下载安装程序。', linux: '选择 AppImage、deb 或 rpm。', tui: '用一条终端命令构建并安装。' }, installMethod: '安装方法', view: '查看 ↓', hide: '收起 ↑', latest: '最新版本', copy: '复制命令', copied: '命令已复制。', copyFailed: '复制失败，请手动复制上面的命令。',
    macTitle: '在 macOS 上安装', macChoose: '请选择以下其中一种方法。', dmg: '通过 DMG 安装', dmgStep1: '：在 Assets 中下载以 universal.dmg 结尾的文件。', dmgStep2: '打开 DMG，将 Ginote 拖到 Applications 文件夹，然后启动应用。', homebrew: '通过 Homebrew 安装', runCommand: '复制以下命令并在终端运行。', linuxTitle: '在 Linux 上安装', linuxIntro: '：在 Assets 中下载适合您发行版的文件。', appImage: '赋予文件执行权限并运行：',
    tuiTitle: '安装终端 TUI', tuiReq: '需要 Go 1.27.1 或更新版本及 C 编译器。将以下命令粘贴到终端，即可从源码构建并安装到 ~/.local/bin/ginote-tui。', tuiAfter: '安装后运行 ginote-tui。如果找不到命令，请将 ~/.local/bin 加入 PATH。', tuiPrebuilt: '预编译文件可在', tuiReleaseLabel: 'GitHub Releases 的 tui-v... 标签', tuiPrebuiltEnd: '中下载。', installScript: '查看安装脚本', tuiDocs: 'TUI 文档',
    windowsTitle: '在 Windows 上安装', windowsIntro: '无需 Microsoft Store，可直接从 GitHub Releases 安装。安装程序没有 Windows 代码签名，首次运行时可能会出现确认提示。', windowsStep1: '：在 Assets 中下载以 x64-setup.exe 结尾的文件。', windowsStep2: '运行下载的安装程序。如果看到“Windows 已保护你的电脑”，请点击“更多信息”。', windowsStep3: '确认文件名与下载的 Ginote 安装程序一致，然后点击“仍要运行”完成安装。', windowsNote: '如果浏览器阻止下载，请在下载列表中打开文件菜单并选择“保留”。先确认文件来源为 github.com/zidell/ginote。如果 Smart App Control 完全阻止该文件，可能不会显示“更多信息”。', exampleLabel: '示例界面 · 可能因 Windows 版本而异', protect: 'Windows 已保护你的电脑', protectMsg: 'Microsoft Defender SmartScreen 阻止了无法识别的应用启动。', moreInfo: '① 更多信息', app: '应用', publisher: '发布者：未知发布者', run: '② 仍要运行', pwa: '也可以从浏览器的“安装应用”菜单安装网页应用。下次打开时会直接进入仓库设置。', source: '源代码'
  },
  ja: {
    ...landingCopy.en,
    tuiWindowsReq: '64ビットの Windows PowerShell で次のコマンドを実行してください。ビルド済みの Windows 実行ファイルをインストールするので、Go や C コンパイラは不要です。', tuiWindowsAfter: 'インストール後、同じ PowerShell で ginote-tui を実行してください。%LOCALAPPDATA%\\Programs\\ginote-tui にインストールし、ユーザーの PATH に追加します。更新時は TUI を終了してから再実行してください。',
    title: 'Ginote — GitHub リポジトリに残るノート', lead: '軽くてシンプルな、自分だけのノートアプリ。ノートは GitHub Issues に保存され、開発環境や MCP ツールでも利用できます。', previewAlt: 'Ginote でノートを開いて編集する画面', start: '始める', download: 'ダウンロード', caption: 'GitHub アカウント、非公開リポジトリ、アクセストークンが必要です。設定は順を追って案内します。', featuresLabel: 'Ginote の特徴', features: [{ title: 'MCP と完全に連携', body: 'ノート自体が GitHub Issues なので、GitHub API と公式 MCP Server でそのまま読み書きできます。' }, { title: 'もう一段階の保護', body: '非公開リポジトリに加え、個々のノート本文を暗号化できます。' }, { title: 'Web・アプリ・ターミナル', body: 'ブラウザー、デスクトップアプリ、TUI で同じリポジトリを使えます。' }], mcpGuide: 'MCP の使い方 ↗',
    cards: { macos: 'DMG または Homebrew でインストールします。', windows: 'Microsoft Store を使わず、インストーラーを直接入手します。', linux: 'AppImage、deb、rpm から選べます。', tui: 'ターミナルのコマンド一つでビルド・インストールします。' }, installMethod: 'インストール方法', view: '見る ↓', hide: '閉じる ↑', latest: '最新リリース', copy: 'コマンドをコピー', copied: 'コマンドをコピーしました。', copyFailed: 'コピーできませんでした。上のコマンドを手動でコピーしてください。',
    macTitle: 'macOS にインストール', macChoose: '次のいずれかを選んでください。', dmg: 'DMG でインストール', dmgStep1: 'の Assets から universal.dmg で終わるファイルをダウンロードします。', dmgStep2: 'DMG を開き、Ginote を Applications フォルダーへドラッグして起動します。', homebrew: 'Homebrew でインストール', runCommand: 'コマンドをコピーしてターミナルで実行します。', linuxTitle: 'Linux にインストール', linuxIntro: 'の Assets からディストリビューションに合うファイルをダウンロードします。', appImage: '実行権限を付けて起動します：',
    tuiTitle: 'ターミナル TUI をインストール', tuiReq: 'Go 1.27.1 以降と C コンパイラーが必要です。次のコマンドを貼り付けると、ソースをビルドして ~/.local/bin/ginote-tui にインストールします。', tuiAfter: 'インストール後に ginote-tui を実行します。見つからなければ ~/.local/bin を PATH に追加してください。', tuiPrebuilt: 'ビルド済みファイルは', tuiReleaseLabel: 'GitHub Releases の tui-v... タグ', tuiPrebuiltEnd: 'から入手できます。', installScript: 'インストールスクリプト', tuiDocs: 'TUI の説明',
    windowsTitle: 'Windows にインストール', windowsIntro: 'Microsoft Store を使わず GitHub Releases から直接インストールします。Windows 用コード署名がないため、初回実行時に確認画面が表示される場合があります。', windowsStep1: 'の Assets から x64-setup.exe で終わるファイルをダウンロードします。', windowsStep2: 'ダウンロードしたファイルを実行します。「Windows によって PC が保護されました」と表示されたら「詳細情報」を押します。', windowsStep3: 'ファイル名が入手した Ginote のインストーラーと一致することを確認し、「実行」を押します。', windowsNote: 'ブラウザーがダウンロードを止めた場合は、ダウンロード一覧のファイルメニューから「保持」を選んでください。まず入手元が github.com/zidell/ginote か確認します。Smart App Control が完全にブロックした場合、「詳細情報」が表示されないことがあります。', exampleLabel: '画面例 · Windows のバージョンで異なります', protect: 'Windows によって PC が保護されました', protectMsg: 'Microsoft Defender SmartScreen が認識できないアプリの起動を防止しました。', moreInfo: '① 詳細情報', app: 'アプリ', publisher: '発行元：不明', run: '② 実行', pwa: 'ブラウザーの「アプリをインストール」メニューから Web アプリとして追加することもできます。次回はリポジトリ設定画面が直接開きます。', source: 'ソースコード'
  }
});

Object.assign(landingCopy, {
  de: {
    ...landingCopy.en,
    tuiWindowsReq: 'Führe diesen Befehl in der 64-Bit-Version von Windows PowerShell aus. Eine fertige Windows-Datei wird installiert; Go und ein C-Compiler sind nicht nötig.', tuiWindowsAfter: 'Starte danach ginote-tui in derselben PowerShell. Die Installation erfolgt in %LOCALAPPDATA%\\Programs\\ginote-tui und ergänzt deinen Benutzer-PATH. Zum Aktualisieren schließe das TUI und führe den Installer erneut aus.',
    title: 'Ginote — Notizen in deinem GitHub-Repository', lead: 'Eine leichte, einfache Notiz-App für dich. Deine Notizen liegen in GitHub Issues und sind auch in deiner Entwicklungsumgebung und mit MCP-Tools verfügbar.', previewAlt: 'Eine geöffnete Notiz in Ginote', start: 'Jetzt starten', download: 'Herunterladen', caption: 'Du brauchst ein GitHub-Konto, ein privates Repository und ein Zugriffstoken. Die Einrichtung führt dich durch alle Schritte.', featuresLabel: 'Ginote-Funktionen', features: [{ title: 'Vollständig mit MCP verbunden', body: 'Notizen sind GitHub Issues und lassen sich direkt über die GitHub API und den offiziellen MCP Server lesen und schreiben.' }, { title: 'Zusätzlicher Schutz', body: 'Das private Repository schützt den Zugriff. Du kannst einzelne Notiztexte zusätzlich verschlüsseln.' }, { title: 'Web, App und Terminal', body: 'Nutze dasselbe Repository im Browser, in der Desktop-App und im TUI.' }], mcpGuide: 'MCP-Anleitung ↗',
    cards: { macos: 'Per DMG oder Homebrew installieren.', windows: 'Installationsdatei direkt herunterladen, ohne Microsoft Store.', linux: 'Zwischen AppImage, deb und rpm wählen.', tui: 'Mit einem Terminalbefehl bauen und installieren.' }, installMethod: 'Installation', view: 'Anzeigen ↓', hide: 'Schließen ↑', latest: 'neueste Version', copy: 'Befehl kopieren', copied: 'Befehl kopiert.', copyFailed: 'Kopieren fehlgeschlagen. Bitte den Befehl oben manuell kopieren.',
    macTitle: 'Auf macOS installieren', macChoose: 'Wähle eine der beiden Methoden.', dmg: 'Mit DMG installieren', dmgStep1: ': Lade unter Assets die Datei herunter, deren Name auf universal.dmg endet.', dmgStep2: 'Öffne die DMG, ziehe Ginote in den Ordner Applications und starte die App.', homebrew: 'Mit Homebrew installieren', runCommand: 'Kopiere die Befehle und führe sie im Terminal aus.', linuxTitle: 'Auf Linux installieren', linuxIntro: ': Lade unter Assets die Datei für deine Distribution herunter.', appImage: 'Mache die Datei ausführbar und starte sie:',
    tuiTitle: 'Terminal-TUI installieren', tuiReq: 'Erfordert Go 1.27.1 oder neuer und einen C-Compiler. Dieser Befehl baut den Quellcode und installiert ihn unter ~/.local/bin/ginote-tui.', tuiAfter: 'Starte danach ginote-tui. Wird der Befehl nicht gefunden, füge ~/.local/bin zum PATH hinzu.', tuiPrebuilt: 'Fertige Binärdateien findest du in', tuiReleaseLabel: 'GitHub Releases unter einem tui-v...-Tag', tuiPrebuiltEnd: '.', installScript: 'Installationsskript', tuiDocs: 'TUI-Dokumentation',
    windowsTitle: 'Auf Windows installieren', windowsIntro: 'Installiere direkt über GitHub Releases, ohne Microsoft Store. Da die Installationsdatei keine Windows-Codesignatur hat, kann beim ersten Start eine Bestätigung erscheinen.', windowsStep1: ': Lade unter Assets die Datei herunter, deren Name auf x64-setup.exe endet.', windowsStep2: 'Starte die heruntergeladene Datei. Wenn „Der Computer wurde durch Windows geschützt“ erscheint, klicke auf „Weitere Informationen“.', windowsStep3: 'Prüfe, ob der Dateiname zum heruntergeladenen Ginote-Installer passt, und klicke auf „Trotzdem ausführen“.', windowsNote: 'Falls der Browser den Download blockiert, öffne die Downloadliste und wähle im Dateimenü „Behalten“. Prüfe zuerst, dass die Quelle github.com/zidell/ginote ist. Wenn Smart App Control die Datei vollständig blockiert, fehlt möglicherweise „Weitere Informationen“.', exampleLabel: 'Beispiel · kann je nach Windows-Version abweichen', protect: 'Der Computer wurde durch Windows geschützt', protectMsg: 'Microsoft Defender SmartScreen hat den Start einer unbekannten App verhindert.', moreInfo: '① Weitere Informationen', app: 'App', publisher: 'Herausgeber: Unbekannt', run: '② Trotzdem ausführen', pwa: 'Du kannst die Web-App auch über „App installieren“ im Browser hinzufügen. Beim nächsten Öffnen erscheint direkt die Repository-Einrichtung.', source: 'Quellcode'
  },
  fr: {
    ...landingCopy.en,
    tuiWindowsReq: 'Exécutez cette commande dans Windows PowerShell 64 bits. Elle installe un exécutable Windows déjà compilé : Go et un compilateur C ne sont pas nécessaires.', tuiWindowsAfter: 'Lancez ensuite ginote-tui dans la même session PowerShell. Le programme est installé dans %LOCALAPPDATA%\\Programs\\ginote-tui et ajouté au PATH utilisateur. Pour le mettre à jour, fermez le TUI et relancez la commande.',
    title: 'Ginote — Vos notes dans votre dépôt GitHub', lead: 'Une application de notes légère et simple, rien que pour vous. Les notes sont des GitHub Issues, accessibles dans votre espace de développement et avec les outils MCP.', previewAlt: 'Une note ouverte dans Ginote', start: 'Commencer', download: 'Télécharger', caption: 'Vous aurez besoin d’un compte GitHub, d’un dépôt privé et d’un jeton d’accès. La configuration vous guidera étape par étape.', featuresLabel: 'Fonctions de Ginote', features: [{ title: 'Intégration complète avec MCP', body: 'Les notes sont des GitHub Issues, lisibles et modifiables directement via l’API GitHub et le MCP Server officiel.' }, { title: 'Une protection supplémentaire', body: 'Le dépôt privé protège déjà l’accès. Vous pouvez aussi chiffrer le contenu de chaque note.' }, { title: 'Web, application, terminal', body: 'Utilisez le même dépôt dans un navigateur, une application installée ou le TUI.' }], mcpGuide: 'Guide MCP ↗',
    cards: { macos: 'Installation par DMG ou Homebrew.', windows: 'Téléchargez directement le programme, sans Microsoft Store.', linux: 'Choisissez AppImage, deb ou rpm.', tui: 'Compilez et installez avec une seule commande.' }, installMethod: 'Installation', view: 'Voir ↓', hide: 'Fermer ↑', latest: 'dernière version', copy: 'Copier la commande', copied: 'Commande copiée.', copyFailed: 'Copie impossible. Copiez la commande ci-dessus manuellement.',
    macTitle: 'Installer sur macOS', macChoose: 'Choisissez une des deux méthodes.', dmg: 'Installer avec un DMG', dmgStep1: ' : dans Assets, téléchargez le fichier dont le nom se termine par universal.dmg.', dmgStep2: 'Ouvrez le DMG, glissez Ginote dans Applications, puis lancez l’application.', homebrew: 'Installer avec Homebrew', runCommand: 'Copiez ces commandes et exécutez-les dans le Terminal.', linuxTitle: 'Installer sur Linux', linuxIntro: ' : dans Assets, téléchargez le fichier adapté à votre distribution.', appImage: 'Rendez le fichier exécutable et lancez-le :',
    tuiTitle: 'Installer le TUI', tuiReq: 'Nécessite Go 1.27.1 ou une version plus récente et un compilateur C. Cette commande compile le code source et l’installe dans ~/.local/bin/ginote-tui.', tuiAfter: 'Lancez ensuite ginote-tui. Si la commande est introuvable, ajoutez ~/.local/bin au PATH.', tuiPrebuilt: 'Les fichiers déjà compilés se trouvent dans', tuiReleaseLabel: 'GitHub Releases sous un tag tui-v...', tuiPrebuiltEnd: '.', installScript: 'Voir le script d’installation', tuiDocs: 'Documentation TUI',
    windowsTitle: 'Installer sur Windows', windowsIntro: 'Installez directement depuis GitHub Releases, sans Microsoft Store. Le programme n’étant pas signé pour Windows, un écran de confirmation peut apparaître au premier lancement.', windowsStep1: ' : dans Assets, téléchargez le fichier dont le nom se termine par x64-setup.exe.', windowsStep2: 'Exécutez le fichier. Si « Windows a protégé votre ordinateur » apparaît, cliquez sur « Informations complémentaires ».', windowsStep3: 'Vérifiez que le nom correspond au programme Ginote téléchargé, puis cliquez sur « Exécuter quand même ».', windowsNote: 'Si le navigateur bloque le téléchargement, ouvrez la liste des téléchargements et choisissez « Conserver » dans le menu du fichier. Vérifiez d’abord que la source est github.com/zidell/ginote. Si Smart App Control bloque complètement le fichier, le bouton « Informations complémentaires » peut être absent.', exampleLabel: 'Exemple · peut varier selon la version de Windows', protect: 'Windows a protégé votre ordinateur', protectMsg: 'Microsoft Defender SmartScreen a empêché le démarrage d’une application non reconnue.', moreInfo: '① Informations complémentaires', app: 'Application', publisher: 'Éditeur : inconnu', run: '② Exécuter quand même', pwa: 'Vous pouvez aussi installer l’application web depuis le menu « Installer l’application » du navigateur. Elle ouvrira ensuite directement la configuration du dépôt.', source: 'Code source'
  }
});

Object.assign(landingCopy, {
  it: {
    ...landingCopy.en,
    tuiWindowsReq: 'Esegui questo comando in Windows PowerShell a 64 bit. Installa un eseguibile Windows già compilato: Go e un compilatore C non sono necessari.', tuiWindowsAfter: 'Poi esegui ginote-tui nella stessa sessione PowerShell. Il programma viene installato in %LOCALAPPDATA%\\Programs\\ginote-tui e aggiunto al PATH utente. Per aggiornare, chiudi il TUI e ripeti il comando.',
    title: 'Ginote — Le tue note nel repository GitHub', lead: 'Un’app di note leggera e semplice, tutta tua. Le note sono GitHub Issues e funzionano anche nel tuo ambiente di sviluppo e con gli strumenti MCP.', previewAlt: 'Una nota aperta in Ginote', start: 'Inizia subito', download: 'Scarica', caption: 'Servono un account GitHub, un repository privato e un token di accesso. La configurazione ti guiderà passo dopo passo.', featuresLabel: 'Funzioni di Ginote', features: [{ title: 'Integrazione completa con MCP', body: 'Le note sono GitHub Issues, leggibili e modificabili tramite l’API GitHub e il MCP Server ufficiale.' }, { title: 'Una protezione in più', body: 'Il repository privato protegge già l’accesso. Puoi anche cifrare il contenuto delle singole note.' }, { title: 'Web, app e terminale', body: 'Usa lo stesso repository nel browser, nell’app installata o nel TUI.' }], mcpGuide: 'Guida MCP ↗',
    cards: { macos: 'Installa con DMG o Homebrew.', windows: 'Scarica il programma direttamente, senza Microsoft Store.', linux: 'Scegli AppImage, deb o rpm.', tui: 'Compila e installa con un solo comando.' }, installMethod: 'Installazione', view: 'Mostra ↓', hide: 'Chiudi ↑', latest: 'ultima versione', copy: 'Copia il comando', copied: 'Comando copiato.', copyFailed: 'Impossibile copiare. Copia manualmente il comando qui sopra.',
    macTitle: 'Installa su macOS', macChoose: 'Scegli uno dei due metodi.', dmg: 'Installa con DMG', dmgStep1: ': in Assets, scarica il file che termina con universal.dmg.', dmgStep2: 'Apri il DMG, trascina Ginote nella cartella Applications e avvia l’app.', homebrew: 'Installa con Homebrew', runCommand: 'Copia i comandi ed eseguili nel Terminale.', linuxTitle: 'Installa su Linux', linuxIntro: ': in Assets, scarica il file adatto alla tua distribuzione.', appImage: 'Rendi il file eseguibile e avvialo:',
    tuiTitle: 'Installa il TUI', tuiReq: 'Richiede Go 1.27.1 o successivo e un compilatore C. Questo comando compila il sorgente e lo installa in ~/.local/bin/ginote-tui.', tuiAfter: 'Esegui ginote-tui dopo l’installazione. Se il comando non viene trovato, aggiungi ~/.local/bin al PATH.', tuiPrebuilt: 'I file già compilati sono in', tuiReleaseLabel: 'GitHub Releases sotto un tag tui-v...', tuiPrebuiltEnd: '.', installScript: 'Vedi lo script di installazione', tuiDocs: 'Documentazione TUI',
    windowsTitle: 'Installa su Windows', windowsIntro: 'Installa direttamente da GitHub Releases, senza Microsoft Store. Poiché il programma non è firmato per Windows, al primo avvio potrebbe apparire una conferma.', windowsStep1: ': in Assets, scarica il file che termina con x64-setup.exe.', windowsStep2: 'Esegui il file scaricato. Se appare “PC protetto da Windows”, fai clic su “Ulteriori informazioni”.', windowsStep3: 'Verifica che il nome corrisponda al programma Ginote scaricato, poi fai clic su “Esegui comunque”.', windowsNote: 'Se il browser blocca il download, apri l’elenco dei download e scegli “Mantieni” dal menu del file. Prima verifica che la fonte sia github.com/zidell/ginote. Se Smart App Control blocca completamente il file, “Ulteriori informazioni” potrebbe non apparire.', exampleLabel: 'Esempio · può variare secondo la versione di Windows', protect: 'PC protetto da Windows', protectMsg: 'Microsoft Defender SmartScreen ha impedito l’avvio di un’app non riconosciuta.', moreInfo: '① Ulteriori informazioni', app: 'App', publisher: 'Autore: sconosciuto', run: '② Esegui comunque', pwa: 'Puoi anche installare la web app dal menu “Installa app” del browser. La prossima volta si aprirà direttamente la configurazione del repository.', source: 'Codice sorgente'
  },
  es: {
    ...landingCopy.en,
    tuiWindowsReq: 'Ejecuta este comando en Windows PowerShell de 64 bits. Instala un ejecutable Windows ya compilado, sin necesitar Go ni un compilador de C.', tuiWindowsAfter: 'Después, ejecuta ginote-tui en la misma sesión de PowerShell. Se instala en %LOCALAPPDATA%\\Programs\\ginote-tui y se añade al PATH del usuario. Para actualizar, cierra el TUI y repite el comando.',
    title: 'Ginote — Tus notas en tu repositorio de GitHub', lead: 'Una aplicación de notas ligera y sencilla, solo para ti. Las notas son GitHub Issues y funcionan en tu espacio de desarrollo y con herramientas MCP.', previewAlt: 'Una nota abierta en Ginote', start: 'Empezar', download: 'Descargar', caption: 'Necesitas una cuenta de GitHub, un repositorio privado y un token de acceso. La configuración te guiará paso a paso.', featuresLabel: 'Funciones de Ginote', features: [{ title: 'Integración completa con MCP', body: 'Las notas son GitHub Issues y se pueden leer y editar mediante la API de GitHub y el MCP Server oficial.' }, { title: 'Una protección adicional', body: 'El repositorio privado ya protege el acceso. También puedes cifrar el contenido de cada nota.' }, { title: 'Web, aplicación y terminal', body: 'Usa el mismo repositorio en el navegador, la aplicación instalada o el TUI.' }], mcpGuide: 'Cómo usar MCP ↗',
    cards: { macos: 'Instala con DMG o Homebrew.', windows: 'Descarga el instalador directamente, sin Microsoft Store.', linux: 'Elige AppImage, deb o rpm.', tui: 'Compila e instala con un solo comando.' }, installMethod: 'Instalación', view: 'Ver ↓', hide: 'Cerrar ↑', latest: 'última versión', copy: 'Copiar comando', copied: 'Comando copiado.', copyFailed: 'No se pudo copiar. Copia manualmente el comando anterior.',
    macTitle: 'Instalar en macOS', macChoose: 'Elige uno de estos métodos.', dmg: 'Instalar desde DMG', dmgStep1: ': en Assets, descarga el archivo que termina en universal.dmg.', dmgStep2: 'Abre el DMG, arrastra Ginote a la carpeta Applications e inicia la aplicación.', homebrew: 'Instalar con Homebrew', runCommand: 'Copia estos comandos y ejecútalos en Terminal.', linuxTitle: 'Instalar en Linux', linuxIntro: ': en Assets, descarga el archivo adecuado para tu distribución.', appImage: 'Da permiso de ejecución al archivo y ábrelo:',
    tuiTitle: 'Instalar el TUI', tuiReq: 'Necesitas Go 1.27.1 o posterior y un compilador C. Este comando compila el código fuente y lo instala en ~/.local/bin/ginote-tui.', tuiAfter: 'Ejecuta ginote-tui después de instalarlo. Si no se encuentra el comando, añade ~/.local/bin a PATH.', tuiPrebuilt: 'Los archivos ya compilados están en', tuiReleaseLabel: 'GitHub Releases bajo una etiqueta tui-v...', tuiPrebuiltEnd: '.', installScript: 'Ver el script de instalación', tuiDocs: 'Documentación del TUI',
    windowsTitle: 'Instalar en Windows', windowsIntro: 'Instala directamente desde GitHub Releases, sin Microsoft Store. Como el instalador no tiene firma de código para Windows, puede aparecer una confirmación la primera vez.', windowsStep1: ': en Assets, descarga el archivo que termina en x64-setup.exe.', windowsStep2: 'Ejecuta el archivo descargado. Si aparece “Windows protegió su PC”, pulsa “Más información”.', windowsStep3: 'Comprueba que el nombre coincide con el instalador de Ginote descargado y pulsa “Ejecutar de todas formas”.', windowsNote: 'Si el navegador bloquea la descarga, abre la lista de descargas y selecciona “Conservar” en el menú del archivo. Comprueba antes que el origen es github.com/zidell/ginote. Si Smart App Control bloquea el archivo por completo, puede que no aparezca “Más información”.', exampleLabel: 'Ejemplo · puede variar según la versión de Windows', protect: 'Windows protegió su PC', protectMsg: 'Microsoft Defender SmartScreen impidió iniciar una aplicación no reconocida.', moreInfo: '① Más información', app: 'Aplicación', publisher: 'Editor: desconocido', run: '② Ejecutar de todas formas', pwa: 'También puedes instalar la aplicación web desde el menú “Instalar aplicación” del navegador. La próxima vez se abrirá directamente la configuración del repositorio.', source: 'Código fuente'
  }
});
